# Generated by Django 4.1.5 on 2023-04-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobseekeruser_type_alter_recruiter_type_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=3),
        ),
    ]
