# Generated by Django 4.1.5 on 2023-04-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
